name: travel_app
description: A simple travel app demonstration

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  sqflite: ^2.2.8
  path: ^1.8.3
  go_router: ^13.0.1
  http: ^0.13.6
  firebase_auth: 4.16.0
  firebase_core: 2.24.2
  firebase_analytics: 10.7.2
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.1.6
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0



  cupertino_icons: ^1.0.5
  provider: ^6.0.4

dev_dependencies:
  intl_utils: ^2.8.4

  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true